/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package at.ac.fhcampuswien

class App {
    // Game logic for a number guessing game

    fun playNumberGame(digitsToGuess: Int = 4) {
        //TODO: build a menu which calls the functions and works with the return values
        val randomNumber = generateRandomNonRepeatingNumber(digitsToGuess)
        var userGuess: Int
        var result: CompareResult

        do {
            println("Guess the $digitsToGuess-digit number:")
            userGuess = readln().toInt() // This will throw a NumberFormatException if the input is not an integer
            result = checkUserInputAgainstGeneratedNumber(userGuess, randomNumber)
            println(result) // This will automatically call toString() from CompareResult
        } while (result.m != digitsToGuess)

        println("Congratulations, you've guessed the correct number: $randomNumber")
    }

    /**
     * Generates a non-repeating number of a specified length between 1-9.
     *
     * Note: The function is designed to generate a number where each digit is unique and does not repeat.
     * It is important to ensure that the length parameter does not exceed the maximum possible length
     * for non-repeating digits (which is 9 excluding 0 for base-10 numbers).
     *
     * @param length The length of the non-repeating number to be generated.
     *               This dictates how many digits the generated number will have.
     * @return An integer of generated non-repeating number.
     *         The generated number will have a number of digits equal to the specified length and will
     *         contain unique, non-repeating digits.
     * @throws IllegalArgumentException if the length is more than 9 or less than 1.
     */
    val generateRandomNonRepeatingNumber: (Int) -> Int = { length ->
        //TODO implement the function
        require(length in 1..9) { "Length must be between 1 and 9" }
        val digits = (1..9).shuffled().take(length).joinToString("")
        digits.toInt()
    }

    /**
     * Compares the user's input integer against a generated number for a guessing game.
     * This function evaluates how many digits the user guessed correctly and how many of those
     * are in the correct position. The game generates number with non-repeating digits.
     *
     * Note: The input and the generated number must both be numbers.
     * If the inputs do not meet these criteria, an IllegalArgumentException is thrown.
     *
     * @param input The user's input integer. It should be a number with non-repeating digits.
     * @param generatedNumber The generated number with non-repeating digits to compare against.
     * @return [CompareResult] with two properties:
     *         1. `n`: The number of digits guessed correctly (regardless of their position).
     *         2. `m`: The number of digits guessed correctly and in the correct position.
     *         The result is formatted as "Output: m:n", where "m" and "n" represent the above values, respectively.
     * @throws IllegalArgumentException if the inputs do not have the same number of digits.
     */
    val checkUserInputAgainstGeneratedNumber: (Int, Int) -> CompareResult = { input, generatedNumber ->
        //TODO implement the function
        val inputStr = input.toString()
        val generatedStr = generatedNumber.toString()

        require(inputStr.length == generatedStr.length) { "Input and generated number must have the same number of digits" }

        var correctPositions = 0 // This will be 'm' in CompareResult
        var correctDigits = 0 // This will be 'n' in CompareResult
        val seen = mutableSetOf<Char>()

        for (i in inputStr.indices) {
            if (inputStr[i] == generatedStr[i]) correctPositions++
            if (inputStr[i] in generatedStr && inputStr[i] !in seen) {
                correctDigits++
                seen.add(inputStr[i])
            }
        }

        CompareResult(correctDigits, correctPositions)
    }
}

fun main() {
    val app = App()
    println("Welcome to the Number Guessing Game!")
    app.playNumberGame()
    // TODO: call the App.playNumberGame function with and without default arguments
}
